const express = require('express');
const mongoose = require('mongoose');
const slug = require('mongoose-slug-updater');
const cookieParser = require('cookie-parser');
const helmet = require('helmet');
const cors = require('cors');
const error = require('../middleware/error.js');
const userRouter = require('../routes/user.js');
const itemRouter = require('../routes/item.js');
const cartRouter = require('../routes/cart.js');
const listRouter = require('../routes/list.js');
const brandRouter = require('../routes/brand.js');
const orderRouter = require('../routes/order.js');
const googleRouter = require('../routes/googleAuth.js');
const categoryRouter = require('../routes/category.js');
const facebookRouter = require('../routes/facebookAuth.js');
mongoose.plugin(slug);

module.exports = function (app) {
	app.use(express.json());
	app.use(express.urlencoded({ extended: true }));
	app.use(express.static('public'));
	app.use(cookieParser());
	app.use(helmet());
	app.use(cors());
	app.use('/api/user', userRouter);
	app.use('/api/item', itemRouter);
	app.use('/api/cart', cartRouter);
	app.use('/api/list', listRouter);
	app.use('/api/brand', brandRouter);
	app.use('/api/order', orderRouter);
	app.use('/auth/google', googleRouter);
	app.use('/api/category', categoryRouter);
	app.use('/auth/facebook', facebookRouter);
	app.use(error);
};
